#!/bin/bash
############## This section states the requirements the job requires:
#SBATCH --job-name=act-teach
#SBATCH --time 1:30:00
#SBATCH -c 1
#SBATCH --mem=1000MB
#SBATCH --ntasks=1
#SBATCH --array=0-%%NUM_ARRAY%%
#SBATCH -o triton_out/debug.out
############## Here starts the actual UNIX commands and payload:

module purge
module load anaconda

srun python main_triton.py $SLURM_ARRAY_TASK_ID

